baseurl = "/"
languageCode = "en-us"
title = "chrisanthropic"
theme = "slim-pickins"
Paginate = 10
disqusShortname = "xxxx"


[params]
  twitterName = ""
  githubName = ""
  stackOverflowId = "#######"
  description = "Demo site for a hugo theme"
  google_analytics = "UA-xxxxxx-xx"

[[menu.main]]
  name = "home"
  identifier = "home"
  url = "/"
  weight = 1

[[menu.main]]
  name = "posts"
  identifier = "posts"
  url = "/posts/"
  weight = 2

[[menu.socials]]
  name = "linkedin"
  identifier = "linkedin"
  url = "https://www.linkedin.com"
  weight = 1

[[menu.socials]]
  name = "tumblr"
  identifier = "tumblr"
  url = "https://www.tumblr.com"
  weight = 2

[[menu.socials]]
  name = "facebook"
  identifier = "facebook"
  url = "https://www.facebook.com"
  weight = 3

[[menu.socials]]
  name = "twitter"
  identifier = "twitter"
  url = "https://www.twitter.com"
  weight = 4

[[menu.socials]]
  name = "github"
  identifier = "github"
  url = "https://www.github.com"
  weight = 5

[[menu.socials]]
  name = "rss"
  identifier = "rss"
  url = "/index.xml"
  weight = 6
