baseurl = "/"
languageCode = "en-us"
title = "chrisanthropic"
theme = "slim-pickins"
Paginate = 10
disqusShortname = "xxxx"


[params]
  twitterName = ""
  githubName = ""
  stackOverflowId = "#######"
  description = "Demo site for a hugo theme"
  google_analytics = "UA-xxxxxx-xx"

[[menu.main]]
  name = "home"
  identifier = "home"
  url = "/"
  weight = 1

[[menu.socials]]
  name = "twitter"
  identifier = "twitter"
  url = "https://www.twitter.com"
  weight = 1

[[menu.socials]]
  name = "github"
  identifier = "github"
  url = "https://www.github.com"
  weight = 2

[[menu.socials]]
  name = "rss"
  identifier = "rss"
  url = "/index.xml"
  weight = 3
